CUDA_VISIBLE_DEVICES=0 python train_dair.py --root=checkpoints \
	--dataset=xmagical --data=/home/junyao/Datasets/xirl/xmagical --batch_size=64 \
	--epochs=100 --weight_decay_norm=1e-2 --num_nf=0 \
	--num_latent_scales=1 --num_groups_per_scale=1 --num_latent_per_group=256 \
	--num_channels_enc=64 --num_channels_dec=64 \
	--num_preprocess_blocks=3 --num_postprocess_blocks=3 \
	--num_preprocess_cells=2 --num_postprocess_cells=2 \
	--num_cell_per_cond_enc=2 --num_cell_per_cond_dec=2 \
	--num_process_per_node=1 \
	--use_se --res_dist \
	--save=vanilla_mask_process_beta=1_01260010 \
	--master_port=6020 \
	--seed=43 \
	--kl_beta=1.0 \
	--cond_robot_mask --process_cond_info \
	--cont_training